name: Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: carsharing
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar
